# 1. Setting Up

In [57]:
import numpy as np

## 2a: More Than One Dimensions

`np.zeros()` and `np.ones()` return the numpy arrays filled respectively with zeros and ones, of the given shape.  

In [58]:
# np.ones actually takes a tuple, specifying the rows and columns of the all ones matrix (2D array)
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


The `reshape` function allows us to take an array and change its shape while maintaining its data.

In [59]:
# Create an array of the values 0 to 20 (exclusive)
x = np.arange(20)
print('Before reshape')
print(x)
print()

Before reshape
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



In [60]:
y = np.reshape(x, (5, 4))
print("After reshape")
print(y)
print()


After reshape
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]



## 2b: Accessing Data

How do we access data at a particular location (e.g., a particular row and column) in an array? This process is referred to as **"indexing"**. If you are selecting multiple rows or columns, it is referred to as **"slicing"**.

In [61]:
# What will this cell output? 

# Access one value
print('First: y[1,2]')
y1 = y[1,2]
print(y1)
print()

First: y[1,2]
6



In [62]:
# Slice both elements of tuple
print('Second: y[0:6, 2:5]')
y2 = y[0:6, 2:5]
print(y2)

Second: y[0:6, 2:5]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]


In [63]:
# Slice notation has a "and everything else" syntax
print('Third: y[1, :]')
y3 = y[1, :]
print(y3) # Everything in the first row
print()

Third: y[1, :]
[4 5 6 7]



In [64]:
print('Fourth: y[:, 3]')
y4 = y[:, 3]
print(y4) # Everything in the third column
print()


Fourth: y[:, 3]
[ 3  7 11 15 19]



## 2c: Shape of Numpy Arrays

We often need to know how many datapoints are in our dataset (num rows), or how many attributes there are per point (num columns). This is referred to as the numpy.array's "shape."

In [65]:
# What do each of these return? How do you interpret the result?

print('y.shape')
print(y.shape)
print()

y.shape
(5, 4)



## 2d: Numpy Functions

Numpy has functions that can be applied to arrays and their subsets! Many of the standard functions we might want to use are supported.
- mean()
- max()
- min()

In [66]:
# Reusing y from above (digits 1 - 20 exclusive, in a 5x4 array)
print('Mean y')
mean = y.mean()
print(mean)

print()

print('min of the second column of y')
min = y[1].min()
print(min)

print()

print('max of the second row')
max = y[1].max()
print(max)

print()

# Technically, we could have also used our knowledge of the data to answer this question without computation.
# We know how the data is distributed across the array; in particular, elements increase left to right and top to bottom.
# Leveraging this knowledge would save us computation in situations with vast, many dimensional arrays.

Mean y
9.5

min of the second column of y
4

max of the second row
7



You can also get apply the function across particular axes. 

In [67]:
# Another syntax for numpy functions across arrays
print(np.max(y, axis=0))

[16 17 18 19]


In [68]:
print(np.max(y, axis=1))

# What are we returning here?

[ 3  7 11 15 19]


Axis 0 is the rows (down the columns), axis 1 is the columns (down the rows).

## 2E: Bincount

In [69]:
z = [1,1,2,5,9,9,8,3,1,4,5,7,1,6,9,0,4,4,1, 15]
z = np.array(z)
print(z)

#TODO: print an array representing the numbers in z in its indices and their counts
#      as the values stored a those indices.  



[ 1  1  2  5  9  9  8  3  1  4  5  7  1  6  9  0  4  4  1 15]


# **How do you find the numpy functions you need? Search Google for "numpy [function description]." Numpy has very useful documentation and examples that can help you understand its functions!**